### ISSUE TITLE
results_match halts when encountering Cyrillic characters

### ISSUE THREAD

**Issue by PlanetHydrangea** [RushFTK/LiquipediaOsuContributeHelper#1]
trying to get the match results for this mp link (112178663) and the program will just stop when it finds a Cyrillic character and it wont output those characters

image below related

![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/160332047/20460dae-26b7-4bd5-b088-b72990e92e07)

**Comment by Voider404** [comment]
Same thing happens with the spanish alphabet. 
(Frosty Boy) vs (Prospero año), the "ñ" is what breaks the script.
Mp link ID - 106228275
![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52542362/17c724ea-bd55-4eef-b190-9fe3ecd814ab)

**Comment by RushFTK** [comment]
confirmed solved.
