### ISSUE TITLE
mp links show invalid mp link

### ISSUE THREAD

**Issue by flapczek** [RushFTK/LiquipediaOsuContributeHelper#10]
When i'm putting mp links I'm getting invalid link errors: 
![image](https://github.com/user-attachments/assets/70b7ac25-107d-49ae-b0a9-7ec5c87e7e94)

When i'm putting room ids only everything is normal:
![image](https://github.com/user-attachments/assets/996a8422-466c-48f2-87cf-3a9f4e22a528)

**Comment by RushFTK** [comment]
Usually you should post id only, but i can add a support that you can paste entire links.

**Comment by flapczek** [comment]
I would appreciate it cuz most of the main sheets has links to copy, not only ids.
