### ISSUE TITLE
results_match missing one of the maps in results.

### ISSUE THREAD

**Issue by Voider404** [RushFTK/LiquipediaOsuContributeHelper#2]
MP ID - https://osu.ppy.sh/community/matches/112592463

During the script work, i encountered an error with the script. It only showed that there are 10 maps played and TB1 wasn't accounted for, despite it being played out as intended. Mainsheet shows 5-6, osuplus plugin when removing the warmups shows 5-6 as well.

Mainsheet link: https://docs.google.com/spreadsheets/d/1xCIAliAAu0UGmy4AJtWA-g2qaj2q1ViusOQ4o6uKeVU/edit#gid=1884011133

Screenshot of the sheet:
![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52542362/84f5e3eb-a770-4ed7-9175-d82390a29713)

Screenshot of the output:
![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52542362/e8397e86-908f-46a8-968c-bee44765856f)

**Comment by RushFTK** [comment]
confirmed solved.
