### ISSUE TITLE
Score not taken, when there is a crash in 1v1 tournament.

### ISSUE THREAD

**Issue by Voider404** [RushFTK/LiquipediaOsuContributeHelper#3]
Mp link - [109059873](https://osu.ppy.sh/community/matches/109059873)
Tournament - https://docs.google.com/spreadsheets/d/1QONh79-IAnKA3SgwrdINn7BSGbWbswFHBun0j94l7j4/edit#gid=1603695911

![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52542362/92b3bf5d-581d-4b79-b74f-f907423b0d96)

Only 5 maps are taken into account, despite 6 being played and them being displayed in mainsheet.

**Comment by RushFTK** [comment]
yes, when lack of enough player play the last game the entire map score dose not count. for judgement if there are ref or other players in room's situation.
so this isn't a bug, after fixing #4 you might know the solution more clearly.
