### ISSUE TITLE
Broken match detected when on mp link everything is fine

### ISSUE THREAD

**Issue by flapczek** [RushFTK/LiquipediaOsuContributeHelper#4]
MP Links: https://osu.ppy.sh/community/matches/110504478 https://osu.ppy.sh/community/matches/110486656
Tournament: https://docs.google.com/spreadsheets/d/1XAb8W9fPsCXJh-bfr_s_4CeXfEq-GExRg2zdGUaSEMY/edit#gid=0

![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52840700/c8571b5e-2139-47d5-b569-7e5e5152ad39)
![image](https://github.com/RushFTK/LiquipediaOsuContributeHelper/assets/52840700/6b22de1c-f796-4613-adec-04b00a0d1bd8)

**Comment by flapczek** [comment]
Apparently even if it shows broken match in the results_match.txt those matches are there without issues idk

**Comment by RushFTK** [comment]
the broken_match is only a hint that they might have some matches without enough players. e.g. someone abort on the mid game.
just aware to manually check when seeing those things.
Will change descripte to more clearly one.
